STARTING = "先發"
BENCH = "替補"

# Scored
SHOT = "投籃"
DUNK = "灌籃"
SUCCESS_FAST_BREAK = "成功的快攻"
FAIL_FAST_BREAK = "快攻2分球投籃沒中"
FAST_BREAK_LIST = [SUCCESS_FAST_BREAK, FAIL_FAST_BREAK]
THREE_POINT_SHOT = "三分"
OTHER_COURT = "遠射"
SCORED_LIST = [SHOT, DUNK, SUCCESS_FAST_BREAK, FAIL_FAST_BREAK, THREE_POINT_SHOT, OTHER_COURT]

CLOSE_RANGE = "近距離"
MID_RANGE = "中距離"